### ISSUE TITLE
Not compatible with .NET Core 1.0 anymore

### ISSUE THREAD

**Issue by dionoid** [ealsur/loganalytics-extensions-logging#2]
Recently the minimal supported dotnet version was changed to .NET Core 1.1, so this library is not working for .NET Core 1.0 anymore. Looking in the code, there seems to be no reason not to support .NET Core 1.0.
As most projects will be on the LTS release (.NET 1.0) and not the Current (.NET 1.1), could the dependency to .NET 1.1 be changed back to .NET 1.0 ?

**Comment by ealsur** [comment]
Sounds fair,  Im on a mountain range with no means to do it right now, will do it first thing on monday :)

________________________________

**Comment by ealsur** [comment]
Closed on https://github.com/ealsur/loganalytics-extensions-logging/commit/e1f5bff489fe70f2a27931135a7053c8204a1159
