### ISSUE TITLE
How do i get the Your_Key_Id

### ISSUE THREAD

**Issue by lars159** [ealsur/loganalytics-extensions-logging#3]
Hi where in azure do i find the "Your_Key_Id" is it on the Log Analytics dashboard?

**Comment by ealsur** [comment]
@lars159 Sorry for the delay.

Check [this article](https://auth0.com/blog/auth0-to-azure-log-analytics/) for graphic instructions on where is the Workspace Id.  Look for the **Creating our Log Analytics Service** section.
